stages:
  - test
  - release

compile:
  stage: test
  image: golang:1.17-alpine
  script:
    - apk add --no-cache --virtual .build-deps git make gcc musl-dev bash tcl
    - go install github.com/mgechev/revive@v1.1.2
    - go install github.com/go-bindata/go-bindata/...@latest
    - go mod tidy
    - make app
    - make test
  tags:
    - offline-test
  artifacts:
    paths:
      - bin

release:
  stage: release
  script:
    - tar zcvf lancelot.tar.gz bin/lancelot
    - upload lancelot.tar.gz lancelot lancelot-$CI_BUILD_TAG
  tags:
    - upload_to_pkgs
  dependencies:
    - compile
  only:
    - tags
