syntax = "proto3";
package lancepb;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.goproto_getters_all) = true;


service Lance {
    rpc Publish(PubRequest) returns (PubResponse);
    rpc PSChannels(PSChannelsRequest) returns (PSChannelsResponse);
    rpc PSNumSub(PSNumSubRequest) returns (PSNumSubResponse);
    rpc PSNumPat(PSNumPatRequest) returns (PSNumPatResponse);
    rpc PFCount(PFCountRequest) returns (PFResponse);
    rpc PFAdd(PFAddRequest) returns (PFResponse);
    rpc PFMerge(PFMergeRequest) returns (PFResponse);
}

message UserDB {
    uint64 user = 1;
    uint64 db = 2;
}

message PFCountRequest {
    UserDB userdb = 1;
    repeated bytes keys = 2;
}

message PFResponse {
    uint64 count = 1;
}

message PFAddRequest {
    UserDB userdb = 1;
    bytes key = 2;
    repeated bytes elements = 3;
}

message PFMergeRequest {
    UserDB userdb = 1;
    bytes destkey = 2;
    repeated bytes sourcekeys = 3;
}

message PubRequestMessage {
    string channel = 1;
    repeated bytes messages = 2;
}

message PubRequest{
    repeated PubRequestMessage messages = 1;
}

message PubResponse {
    repeated int64 counts = 1;
}

message PSChannelsRequest {
    string pattern = 1;
}

message PSChannelsResponse {
    repeated string channels = 1;
}

message PSNumSubRequest {
    repeated string channels = 1;
}

message PSNumSubResponse {
    repeated int64 counts = 1;
}

message PSNumPatRequest {
}

message PSNumPatResponse{
    int64 count = 1;
}