package command

import "gitlab.s.upyun.com/platform/lancelot/redcon"

const (
	KEYSPACE_CATEGORY    = "keyspace"
	READ_CATEGORY        = "read"
	WRITE_CATEGORY       = "write"
	SET_CATEGORY         = "set"
	SORTEDSET_CATEGORY   = "sortedset"
	LIST_CATEGORY        = "list"
	HASH_CATEGORY        = "hash"
	STRING_CATEGORY      = "string"
	BITMAP_CATEGORY      = "bitmap"
	HYPERLOGLOG_CATEGORY = "hyperloglog"
	GEO_CATEGORY         = "geo"
	STREAM_CATEGORY      = "stream"
	PUBSUB_CATEGORY      = "pubsub"
	AMDIN_CATEGORY       = "admin"
	FAST_CATEGORY        = "fast"
	SLOW_CATEGORY        = "slow"
	BLOCKING_CATEGORY    = "blocking"
	DANGEROUS_CATEGORY   = "dangerous"
	CONNECTION_CATEGORY  = "connection"
	TRANSCATION_CATEGORY = "transaction"
	SCRIPTING_CATEGORY   = "scripting"

	JSONSET_COMMAND      = "json.set"
	JSONGET_COMMAND      = "json.get"
	JSONDEL_COMMAND      = "json.del"
	HLEN_COMMAND         = "hlen"
	HSET_COMMAND         = "hset"
	HSETNX_COMMAND       = "hsetnx"
	HMSET_COMMAND        = "hmset"
	HGET_COMMAND         = "hget"
	HSTRLEN_COMMAND      = "hstrlen"
	HMGET_COMMAND        = "hmget"
	HGETALL_COMMAND      = "hgetall"
	HRANDFIELD_COMMAND   = "hrandfield"
	HKEYS_COMMAND        = "hkeys"
	HVALS_COMMAND        = "hvals"
	HSCAN_COMMAND        = "hscan"
	HEXISTS_COMMAND      = "hexists"
	HDEL_COMMAND         = "hdel"
	HINCRBY_COMMAND      = "hincrby"
	HINCRBYFLOAT_COMMAND = "hincrbyfloat"
	LPUSH_COMMAND        = "lpush"
	LPUSHX_COMMAND       = "lpushx"
	LPOP_COMMAND         = "lpop"
	RPUSH_COMMAND        = "rpush"
	RPUSHX_COMMAND       = "rpushx"
	LINDEX_COMMAND       = "lindex"
	LINSERT_COMMAND      = "linsert"
	BLPOP_COMMAND        = "blpop"
	BRPOP_COMMAND        = "brpop"
	BRPOPLPUSH_COMMAND   = "brpoplpush"
	BLMOVE_COMMAND       = "blmove"
	RPOP_COMMAND         = "rpop"
	LMOVE_COMMAND        = "lmove"
	RPOPLPUSH_COMMAND    = "rpoplpush"
	LREM_COMMAND         = "lrem"
	LSET_COMMAND         = "lset"
	LLEN_COMMAND         = "llen"
	LRANGE_COMMAND       = "lrange"
	LINFO_COMMAND        = "linfo"
	LTRIM_COMMAND        = "ltrim"
	LPOS_COMMAND         = "lpos"
	SET_COMMAND          = "set"
	MSET_COMMAND         = "mset"
	SETRANGE_COMMAND     = "setrange"
	MSETNX_COMMAND       = "msetnx"
	SETNX_COMMAND        = "setnx"
	SETEX_COMMAND        = "setex"
	PSETEX_COMMAND       = "psetex"
	SETXX_COMMAND        = "setxx"
	GET_COMMAND          = "get"
	MGET_COMMAND         = "mget"
	GETDEL_COMMAND       = "getdel"
	GETSET_COMMAND       = "getset"
	GETEX_COMMAND        = "getex"
	GETRANGE_COMMAND     = "getrange"
	STRLEN_COMMAND       = "strlen"
	APPEND_COMMAND       = "append"
	INCR_COMMAND         = "incr"
	INCRBY_COMMAND       = "incrby"
	INCRBYFLOAT_COMMAND  = "incrbyfloat"
	DECR_COMMAND         = "decr"
	DECRBY_COMMAND       = "decrby"
	BITCOUNT_COMMAND     = "bitcount"
	BITPOS_COMMAND       = "bitpos"
	GETBIT_COMMAND       = "getbit"
	BITOP_COMMAND        = "bitop"
	SETBIT_COMMAND       = "setbit"
	BITFIELD_COMMAND     = "bitfield"
	DEL_COMMAND          = "del"
	SCAN_COMMAND         = "scan"
	ALL_COMMAND          = "all"
	TTL_COMMAND          = "ttl"
	EXPIRE_COMMAND       = "expire"
	OBJECT_COMMAND       = "object"
	XADD_COMMAND         = "xadd"
	XRANGE_COMMAND       = "xrange"
	XGROUP_COMMAND       = "xgroup"
	CREATE_COMMAND       = "create"
	DESTORY_COMMAND      = "destroy"
	SETID_COMMAND        = "setid"
	CREATECONSUMER       = "createconsumer"
	DELCONSUMER          = "delconsumer"
	PUBLISH_COMMAND      = "publish"
	PUBSUB_COMMAND       = "pubsub"
	CHANNELS_COMMAND     = "channels"
	NUMSUB_COMMAND       = "numsub"
	NUMPAT_COMMAND       = "numpat"
	SUBSCRIBE_COMMAND    = "subscribe"
	PSUBSCRIBE_COMMAND   = "psubscribe"
	UNSUBSCRIBE_COMMAND  = "unsubscribe"
	PUNSUBSCRIBE_COMMAND = "punsubscribe"
	FSUBSCRIBE_COMMAND   = "fsubscribe"
	HELP_COMMAND         = "help"
	ENCODING_COMMAND     = "encoding"
	FREQ_COMMAND         = "freq"
	IDLETIME_COMMAND     = "idletime"
	REFCOUNT_COMMAND     = "refcount"
	EVAL_COMMAND         = "eval"
	EVALSHA_COMMAND      = "evalsha"
	EVAL_RO_COMMAND      = "eval_ro"
	EVALSHA_RO_COMMAND   = "evalsha_ro"
	SCRIPT_COMMAND       = "script"
	LOAD_COMMAND         = "load"
	FLUSH_COMMAND        = "flush"
	EXISTS_COMMAND       = "exists"
	KILL_COMMAND         = "kill"
	AUTH_COMMAND         = "auth"
	SELECT_COMMAND       = "select"
	FLUSHALL_COMMAND     = "flushall"
	FLUSHDB_COMMAND      = "flushdb"
	ACL_COMMAND          = "acl"
	CAT_COMMAND          = "cat"
	DELUSER_COMMAND      = "deluser"
	GENPASS_COMMAND      = "genpass"
	GETUSER_COMMAND      = "getuser"
	SETUSER_COMMAND      = "setuser"
	USERS_COMMAND        = "users"
	LIST_COMMAND         = "list"
	SAVE_COMMAND         = "save"
	PING_COMMAND         = "ping"
	SHUTDONW_COMMAND     = "shutdown"
	WATCH_COMMAND        = "watch"
	EXEC_COMMAND         = "exec"
	MULTI_COMMAND        = "multi"
	DISCARD_COMMAND      = "discard"

	MAX_COMMANDS   = 1024
	MAX_KEY_SIZE   = 4 * 1024
	MAX_VALUE_SIZE = 5 * 1024 * 1024

	ASYNC_OPTION = "async"
	SYNC_OPTION  = "sync"

	OK          = redcon.SimpleString("OK")
	Queued      = redcon.SimpleString("QUEUED")
	PONG        = redcon.SimpleString("PONG")
	EmptyString = redcon.SimpleString("")

	DataPrefix  = 'd'
	UserPrefix  = 'u'
	CountPrefix = 'c'
	TTLPrefix   = 't'

	GenericCursor = "g"
	HashCursor    = "h"
)

var (
	EmptySlice  = []struct{}{}
	EmptyCursor = []interface{}{0, [][]byte{}}
)

func SimpleInt(n int64) redcon.SimpleInt {
	return redcon.SimpleInt(n)
}

func SimpleString(n string) redcon.SimpleString {
	return redcon.SimpleString(n)
}
