package command

import (
	_ "embed"

	"gitlab.s.upyun.com/platform/lancelot/redcon"
)

const (
	KEYSPACE_CATEGORY    = "keyspace"
	READ_CATEGORY        = "read"
	WRITE_CATEGORY       = "write"
	SET_CATEGORY         = "set"
	SORTEDSET_CATEGORY   = "sortedset"
	LIST_CATEGORY        = "list"
	HASH_CATEGORY        = "hash"
	STRING_CATEGORY      = "string"
	BITMAP_CATEGORY      = "bitmap"
	HYPERLOGLOG_CATEGORY = "hyperloglog"
	GEO_CATEGORY         = "geo"
	STREAM_CATEGORY      = "stream"
	PUBSUB_CATEGORY      = "pubsub"
	AMDIN_CATEGORY       = "admin"
	FAST_CATEGORY        = "fast"
	SLOW_CATEGORY        = "slow"
	BLOCKING_CATEGORY    = "blocking"
	DANGEROUS_CATEGORY   = "dangerous"
	CONNECTION_CATEGORY  = "connection"
	TRANSCATION_CATEGORY = "transaction"
	SCRIPTING_CATEGORY   = "scripting"

	JSONSET_COMMAND              = "json.set"
	JSONGET_COMMAND              = "json.get"
	JSONDEL_COMMAND              = "json.del"
	JSONCLEAR_COMMAND            = "json.clear"
	JSONTYPE_COMMAND             = "json.type"
	JSONMGET_COMMAND             = "json.mget"
	JSONOBJKEYS_COMMAND          = "json.objkeys"
	JSONOBJLEN_COMMAND           = "json.objlen"
	JSONARRLEN_COMMAND           = "json.arrlen"
	JSONARRINDEX_COMMAND         = "json.arrindex"
	JSONARRAPPEND_COMMAND        = "json.arrappend"
	JSONARRINSERT_COMMAND        = "json.arrinsert"
	JSONARRPOP_COMMAND           = "json.arrpop"
	JSONARRTRIM_COMMAND          = "json.arrtrim"
	JSONTOGGLE_COMMAND           = "json.toggle"
	ZCARD_COMMAND                = "zcard"
	ZCOUNT_COMMAND               = "zcount"
	ZPOPMIN_COMMAND              = "zpopmin"
	ZPOPMAX_COMMAND              = "zpopmax"
	BZPOPMIN_COMMAND             = "bzpopmin"
	BZPOPMAX_COMMAND             = "bzpopmax"
	ZRANGEBYSCORE_COMMAND        = "zrangebyscore"
	ZRANGEBYLEX_COMMAND          = "zrangebylex"
	ZLEXCOUNT_COMMAND            = "zlexcount"
	ZRANK_COMMAND                = "zrank"
	ZREVRANK_COMMAND             = "zrevrank"
	ZREVRANGEBYLEX_COMMAND       = "zrevrangebylex"
	ZREVRANGEBYSCORE_COMMAND     = "zrevrangebyscore"
	ZSCORE_COMMAND               = "zscore"
	ZMSCORE_COMMAND              = "zmscore"
	ZINCRBY_COMMAND              = "zincrby"
	ZRANGE_COMMAND               = "zrange"
	ZRANDMEMBER_COMMAND          = "zrandmember"
	ZREVRANGE_COMMAND            = "zrevrange"
	ZREMRANGEBYRANK_COMMAND      = "zremrangebyrank"
	ZREMRANGEBYSCORE_COMMAND     = "zremrangebyscore"
	ZREMRANGEBYLEX_COMMAND       = "zremrangebylex"
	ZDIFF_COMMAND                = "zdiff"
	ZDIFFSTORE_COMMAND           = "zdiffstore"
	ZINTER_COMMAND               = "zinter"
	ZINTERCARD_COMMAND           = "zintercard"
	ZINTERSTORE_COMMAND          = "zinterstore"
	ZUNION_COMMAND               = "zunion"
	ZUNIONSTORE_COMMAND          = "zunionstore"
	ZRANGESTORE_COMMAND          = "zrangestore"
	ZSCAN_COMMAND                = "zscan"
	ZADD_COMMAND                 = "zadd"
	ZREM_COMMAND                 = "zrem"
	SADD_COMMAND                 = "sadd"
	SISMEMBER_COMMAND            = "sismember"
	SMISMEMBER_COMMAND           = "smismember"
	SPOP_COMMAND                 = "spop"
	SMEMBERS_COMMAND             = "smembers"
	SRANDMEMBER_COMMAND          = "srandmember"
	SSCAN_COMMAND                = "sscan"
	SREM_COMMAND                 = "srem"
	SDIFF_COMMAND                = "sdiff"
	SINTER_COMMAND               = "sinter"
	SUNION_COMMAND               = "sunion"
	SUNIONSTORE_COMMAND          = "sunionstore"
	SDIFFSTORE_COMMAND           = "sdiffstore"
	SINTERSTORE_COMMAND          = "sinterstore"
	SCARD_COMMAND                = "scard"
	SMOVE_COMMAND                = "smove"
	HLEN_COMMAND                 = "hlen"
	HSET_COMMAND                 = "hset"
	HSETNX_COMMAND               = "hsetnx"
	HMSET_COMMAND                = "hmset"
	HGET_COMMAND                 = "hget"
	HSTRLEN_COMMAND              = "hstrlen"
	HMGET_COMMAND                = "hmget"
	HGETALL_COMMAND              = "hgetall"
	HRANDFIELD_COMMAND           = "hrandfield"
	HKEYS_COMMAND                = "hkeys"
	HVALS_COMMAND                = "hvals"
	HSCAN_COMMAND                = "hscan"
	HEXISTS_COMMAND              = "hexists"
	HDEL_COMMAND                 = "hdel"
	HINCRBY_COMMAND              = "hincrby"
	HINCRBYFLOAT_COMMAND         = "hincrbyfloat"
	LPUSH_COMMAND                = "lpush"
	LPUSHX_COMMAND               = "lpushx"
	LPOP_COMMAND                 = "lpop"
	RPUSH_COMMAND                = "rpush"
	RPUSHX_COMMAND               = "rpushx"
	LINDEX_COMMAND               = "lindex"
	LINSERT_COMMAND              = "linsert"
	BLPOP_COMMAND                = "blpop"
	BRPOP_COMMAND                = "brpop"
	BRPOPLPUSH_COMMAND           = "brpoplpush"
	BLMOVE_COMMAND               = "blmove"
	RPOP_COMMAND                 = "rpop"
	LMOVE_COMMAND                = "lmove"
	RPOPLPUSH_COMMAND            = "rpoplpush"
	LREM_COMMAND                 = "lrem"
	LSET_COMMAND                 = "lset"
	LLEN_COMMAND                 = "llen"
	LRANGE_COMMAND               = "lrange"
	LINFO_COMMAND                = "linfo"
	LTRIM_COMMAND                = "ltrim"
	LPOS_COMMAND                 = "lpos"
	SET_COMMAND                  = "set"
	MSET_COMMAND                 = "mset"
	SETRANGE_COMMAND             = "setrange"
	MSETNX_COMMAND               = "msetnx"
	SETNX_COMMAND                = "setnx"
	SETEX_COMMAND                = "setex"
	PSETEX_COMMAND               = "psetex"
	SETXX_COMMAND                = "setxx"
	GET_COMMAND                  = "get"
	GETLOCAL_COMMAND             = "getlocal"
	MGET_COMMAND                 = "mget"
	GETDEL_COMMAND               = "getdel"
	GETSET_COMMAND               = "getset"
	GETEX_COMMAND                = "getex"
	GETRANGE_COMMAND             = "getrange"
	STRLEN_COMMAND               = "strlen"
	APPEND_COMMAND               = "append"
	INCR_COMMAND                 = "incr"
	INCRBY_COMMAND               = "incrby"
	INCRBYFLOAT_COMMAND          = "incrbyfloat"
	DECR_COMMAND                 = "decr"
	DECRBY_COMMAND               = "decrby"
	BITCOUNT_COMMAND             = "bitcount"
	BITPOS_COMMAND               = "bitpos"
	GETBIT_COMMAND               = "getbit"
	BITOP_COMMAND                = "bitop"
	SETBIT_COMMAND               = "setbit"
	BITFIELD_COMMAND             = "bitfield"
	DEL_COMMAND                  = "del"
	RENAME_COMMAND               = "rename"
	RENAMENX_COMMAND             = "renamenx"
	UNLINK_COMMAND               = "unlink"
	TYPE_COMMAND                 = "type"
	SCAN_COMMAND                 = "scan"
	KEYS_COMMAND                 = "keys"
	ALL_COMMAND                  = "all"
	TOUCH_COMMAND                = "touch"
	TTL_COMMAND                  = "ttl"
	PTTL_COMMAND                 = "pttl"
	EXPIRE_COMMAND               = "expire"
	EXPIREAT_COMMAND             = "expireat"
	EXPIRETIME_COMMAND           = "expiretime"
	PEXPIRE_COMMAND              = "pexpire"
	PEXPIREAT_COMMAND            = "pexpireat"
	PEXPIRETIME_COMMAND          = "pexpiretime"
	PERSIST_COMMAND              = "persist"
	OBJECT_COMMAND               = "object"
	XADD_COMMAND                 = "xadd"
	XRANGE_COMMAND               = "xrange"
	XGROUP_COMMAND               = "xgroup"
	CREATE_COMMAND               = "create"
	DESTORY_COMMAND              = "destroy"
	SETID_COMMAND                = "setid"
	CREATECONSUMER               = "createconsumer"
	DELCONSUMER                  = "delconsumer"
	PUBLISH_COMMAND              = "publish"
	PUBSUB_COMMAND               = "pubsub"
	CHANNELS_COMMAND             = "channels"
	NUMSUB_COMMAND               = "numsub"
	NUMPAT_COMMAND               = "numpat"
	SUBSCRIBE_COMMAND            = "subscribe"
	PSUBSCRIBE_COMMAND           = "psubscribe"
	UNSUBSCRIBE_COMMAND          = "unsubscribe"
	PUNSUBSCRIBE_COMMAND         = "punsubscribe"
	FSUBSCRIBE_COMMAND           = "fsubscribe"
	GEOADD_COMMAND               = "geoadd"
	GEOHASH_COMMAND              = "geohash"
	GEOPOS_COMMAND               = "geopos"
	GEORADIUS_COMMAND            = "georadius"
	GEORADIUS_RO_COMMAND         = "georadius_ro"
	GEORADIUSBYMEMBER_COMMAND    = "georadiusbymember"
	GEORADIUSBYMEMBER_RO_COMMAND = "georadiusbymember_ro"
	GEOSEARCH_COMMAND            = "geosearch"
	GEODIST_COMMAND              = "geodist"
	GEOREM_COMMAND               = "georem"
	PFADD_COMMAND                = "pfadd"
	PFCOUNT_COMMAND              = "pfcount"
	PFMERGE_COMMAND              = "pfmerge"
	HELP_COMMAND                 = "help"
	ENCODING_COMMAND             = "encoding"
	FREQ_COMMAND                 = "freq"
	IDLETIME_COMMAND             = "idletime"
	REFCOUNT_COMMAND             = "refcount"
	EVAL_COMMAND                 = "eval"
	EVALSHA_COMMAND              = "evalsha"
	EVAL_RO_COMMAND              = "eval_ro"
	EVALSHA_RO_COMMAND           = "evalsha_ro"
	SCRIPT_COMMAND               = "script"
	LOAD_COMMAND                 = "load"
	FLUSH_COMMAND                = "flush"
	EXISTS_COMMAND               = "exists"
	KILL_COMMAND                 = "kill"
	AUTH_COMMAND                 = "auth"
	SELECT_COMMAND               = "select"
	CLIENT_COMMAND               = "client"
	ID_COMMAND                   = "id"
	INFO_COMMAND                 = "info"
	SETNAME_COMMAND              = "setname"
	GETNAME_COMMAND              = "getname"
	FLUSHALL_COMMAND             = "flushall"
	FLUSHDB_COMMAND              = "flushdb"
	DBSIZE_COMMAND               = "dbsize"
	ROLE_COMMAND                 = "role"
	TIME_COMMAND                 = "time"
	ACL_COMMAND                  = "acl"
	CONFIG_COMMAND               = "config"
	RESETSTAT_COMMAND            = "resetstat"
	REWRITE_COMMAND              = "rewrite"
	CAT_COMMAND                  = "cat"
	DELUSER_COMMAND              = "deluser"
	GENPASS_COMMAND              = "genpass"
	GETUSER_COMMAND              = "getuser"
	SETUSER_COMMAND              = "setuser"
	USERS_COMMAND                = "users"
	LIST_COMMAND                 = "list"
	UNBLOCK_COMMAND              = "unblock"
	WHOAMI_COMMAND               = "whoami"
	COMMAND_COMMAND              = "command"
	SAVE_COMMAND                 = "save"
	PING_COMMAND                 = "ping"
	ECHO_COMMAND                 = "echo"
	QUIT_COMMAND                 = "quit"
	SHUTDONW_COMMAND             = "shutdown"
	WATCH_COMMAND                = "watch"
	UNWATCH_COMMAND              = "unwatch"
	EXEC_COMMAND                 = "exec"
	MULTI_COMMAND                = "multi"
	DISCARD_COMMAND              = "discard"
	SENTINEL_COMMAND             = "sentinel"
	MASTER_COMMAND               = "master"
	MASTERS_COMMAND              = "masters"
	SLAVES_COMMAND               = "slaves"
	MASTERBYNAME_COMMAND         = "get-master-addr-by-name"
	SENTINELS_COMMAND            = "sentinels"

	MAX_COMMANDS   = 1024
	MINI_SCAN_SIZE = 256

	ASYNC_OPTION = "async"
	SYNC_OPTION  = "sync"

	OK          = redcon.SimpleString("OK")
	Queued      = redcon.SimpleString("QUEUED")
	PONG        = redcon.SimpleString("PONG")
	EmptyString = redcon.SimpleString("")
	BUSYPONG    = redcon.SimpleString("BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.")

	DataPrefix   PrefixType = 'd'
	UserPrefix   PrefixType = 'u'
	CountPrefix  PrefixType = 'c'
	CountGeneral PrefixType = 'C'
	TTLPrefix    PrefixType = 't'
	KeyPrefix    PrefixType = 'k'
	ValuePrefix  PrefixType = 'v'

	GenericCursor = "g"
)

type PrefixType byte

var (
	EmptySlice     = []struct{}{}
	EmptyCursor    = []interface{}{0, [][]byte{}}
	EmptyBytes     = [][]byte{}
	EmptyInterface = []interface{}{}

	KEYSIZE = []byte("size")
)

func SimpleInt(n int64) redcon.SimpleInt {
	return redcon.SimpleInt(n)
}

func SimpleString(n string) redcon.SimpleString {
	return redcon.SimpleString(n)
}

// Got from redis 6.2.4 with
// echo 'COMMAND' | nc redis_addr redis_port
//go:embed commands.data
var COMMANDS []byte
